spring:
  application:
    name: catalog-dev

server:
  port: 8080

logging:
  level:
    com.tiquetera: DEBUG
    
# Development specific settings
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
